INSERT INTO book_entity (title, author) VALUES ('Hobbit', 'J.R.R. Tolkien');
INSERT INTO book_entity (title, author) VALUES ('Władca Pierścieni', 'J.R.R. Tolkien');
INSERT INTO book_entity (title, author) VALUES ('Silmarillion', 'J.R.R. Tolkien');
INSERT INTO book_entity (title, author) VALUES ('1984', 'George Orwell');
INSERT INTO book_entity (title, author) VALUES ('Folwark zwierzęcy', 'George Orwell');
INSERT INTO book_entity (title, author) VALUES ('Rok 451 Fahrenheita', 'Ray Bradbury');
INSERT INTO book_entity (title, author) VALUES ('Solaris', 'Stanisław Lem');
INSERT INTO book_entity (title, author) VALUES ('Cyberiada', 'Stanisław Lem');
INSERT INTO book_entity (title, author) VALUES ('Bajki robotów', 'Stanisław Lem');
INSERT INTO book_entity (title, author) VALUES ('Dzienniki gwiazdowe', 'Stanisław Lem');
INSERT INTO book_entity (title, author) VALUES ('Mistrz i Małgorzata', 'Michaił Bułhakow');
INSERT INTO book_entity (title, author) VALUES ('Zbrodnia i kara', 'Fiodor Dostojewski');
INSERT INTO book_entity (title, author) VALUES ('Bracia Karamazow', 'Fiodor Dostojewski');
INSERT INTO book_entity (title, author) VALUES ('Idiota', 'Fiodor Dostojewski');
INSERT INTO book_entity (title, author) VALUES ('Proces', 'Franz Kafka');
INSERT INTO book_entity (title, author) VALUES ('Zamek', 'Franz Kafka');
INSERT INTO book_entity (title, author) VALUES ('Przemiana', 'Franz Kafka');
INSERT INTO book_entity (title, author) VALUES ('Duma i uprzedzenie', 'Jane Austen');
INSERT INTO book_entity (title, author) VALUES ('Emma', 'Jane Austen');
INSERT INTO book_entity (title, author) VALUES ('Rozważna i romantyczna', 'Jane Austen');
